template = ""
rev_id = 5
template_sha = "b1bcc12f5675c5b86f53da0a290c53417f28d6e3"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "se"
__UND2C_TRG__ = "es"
__UNDEFINED_SOURCE__ = "North Sámi"
__UNDEFINED_TARGET__ = "Spanish"
__UND_SRC__ = "sme"
__UND_TRG__ = "spa"
