remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for North Sámi ⇒ Spanish
description: An electronic dictionary from North Sámi to Spanish
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: minimal
